### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by ritisha2000** [UBC-MDS/pokehelpyer#16]
"Outline the package you would like to build in the README.md file. In particular, your README.md should contain:

- a summary paragraph that describes the project at a high level

- a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well)."

**Comment by j99thoms** [comment]
Completed with https://github.com/UBC-MDS/pokehelpyer/pull/17 and also https://github.com/UBC-MDS/pokehelpyer/pull/18/commits/406ff4581c29d1a2e99e6403c9524b18ab8f0a3f from https://github.com/UBC-MDS/pokehelpyer/pull/18.
