### ISSUE TITLE
Revision of function specifications

### ISSUE THREAD

**Issue by j99thoms** [UBC-MDS/pokehelpyer#21]
Before we begin the main work of milestone 2 (writing unit tests and codes for our functions), I think we should consider some modifications to our function specifications. Use this issue for communications on this topic.

**Comment by j99thoms** [comment]
**1. Rename `add_team_members` to `get_types`:** 
As is, `recommend` takes as input a list `current_team` of up to 5 pokemon names. This list would then be immediately passed to `add_team_members`, which takes as input a list `pokemon_names` of pokemon names, and returns as output as a corresponding list of pokemon types.  For this reason, I think it makes sense to rename `add_team_members` to `get_types`, as that seems to be a more accurate description of the function's purpose. This new name would also make sense since the current docstring for the function is `"Given a list of pokémon names, determine the types of those pokémon using an existing dataset."`

**Comment by j99thoms** [comment]
**2. Consider the existence of dual-type pokémon:**
One detail that was neglected in milestone 1 is the fact that some pokemon can have two types, rather than just one. This complicates some things.

- **2.1. Double weaknesses and resistances:** 
Some dual-typed pokemon can be doubly weak or doubly resistant to certain types. For example, [Abomasnow](https://bulbapedia.bulbagarden.net/wiki/Abomasnow_(Pok%C3%A9mon)) is both Ice-type and Grass-type, and as a result, is doubly weak to Fire-type attacks.  Another example is [Skarmory](https://bulbapedia.bulbagarden.net/wiki/Skarmory_(Pok%C3%A9mon)) which is both Steel-type and Flying-type, and as a result, is doubly resistant to Bug-type attacks and Grass-type attacks. 
In my opinion, the simplest solution is to make a double weakness/resistance count twice when creating the dictionaries for `calc_weaknesses`/`calc_resistances`. For example, if Abomasnow was on a team, then the entry for `'fire'` in the dictionary from `calc_weaknesses` should receive a `+2` from Abomasnow. 

- **2.2. Cancelling out weaknesses and resistances:** 
Some dual-typed pokemon can have a weakness cancel out with a resistance. For an example, we can consider Skarmory yet again. Flying-type pokemon are weak to Rock-type and Ice-type attacks, but Steel-type pokemon are resistant to Rock-type and Ice-type attacks. As a result, Skarmory takes normal damage from Rock-type and Ice-type attacks.
In my opinion, the simplest solution is to make a cancelled-out weakness/resistance not count at all.  For example, if Skarmory was on a team, then the entries for `'rock'` and `'ice'` in the dictionaries from `calc_weaknesses` and `calc_resistances` should both receive no contribution from Skarmory. 

- After implementing changes **2.1** and **2.2**, the keys of the dictionary output by `calc_weaknesses` would still be the same (18 keys for the 18 types in the game), and the values would still be integers, but rather than being the "number of pokemon on the team weak to that type (key)", it would just serve as a measure of the total amount of weakness the team has to that type (key). Similarly for `calc_resistances`. In order to account for cancelling out as detailed in **2.2**, the output of `get_types` would need to be altered to be a list of lists. For example, `get_types(['Pikachu', 'Skarmory', 'Abomasnow'])` would output `[['Electric'], ['Steel', 'Flying'], ['Grass', 'Ice']]`.

**Comment by j99thoms** [comment]
**3. Consider the existence of type immunities:**
Another detail that was neglected in milestone 1 is the fact that some pokemon types are completely immune to other pokemon types. For example, ghost-type pokemon are immune to normal-type attacks, and flying-type pokemon are immune to ground-type attacks. This should clearly contribute some amount to the values in the dictionary from `calc_resistances`. The only question is how much. Given that a double resistance will count as `+2`, I think an immunity needs to count for more since a double resistance is equivalent to $\frac{1}{4}\times$ damage, but an immunity is equivalent to $0\times$ damage. Perhaps `+4` for immunity would be appropriate? For example, if Skarmory (a flying type), was on a team, then the entry for `'ground'` in the dictionary from `calc_resistances` should receive a `+4` from Skarmory.

**Comment by j99thoms** [comment]
**4. Clarify the specifications of `recommend`:**
Currently, the docstring of `recommend` is `"recommend a pokémon that could be added to the current team to make its weaknesses and resistances more balanced."` The idea of the function is to use the information in the dictionaries created by `calc_weaknesses` and `calc_resistances` to determine which pokemon would make the team more "balanced". In order to do this, it seems appropriate that we should first define a metric to measure how "balanced" a team is. To this end, I suggest that we consider using something like the following: 
> For $i=1,2,\dots, 18$, let $w_i$ be the value corresponding to the $i$ -th pokemon type in the dictionary returned by `calc_weaknesses` and let $r_i$ be the value corresponding to the $i$ -th pokemon type in the dictionary returned by `calc_resistances`. Now define $\delta_i = r_i -  w_i$. If $\delta_i < 0$, then the team is weak (overall) to pokemon type $i$, and this should definitely be considered. The more negative $\delta_i$ is, the more problematic. For example, if a player used a team of 5 fire type pokemon, then $\delta_{\text{water}}$ would be equal to -5, and this would be a big problem. If $\delta_i > 0$, then the team is resistant (overall) to pokemon type $i$, which is a good thing. The more positive the better, but any value greater than zero is good. 
> So in my opinion, I think we should penalize negative $\delta_i$ values more than we reward positive $\delta_i$ values. For this reason, I suggest we define the `type-advantage`, $TA$, corresponding to the $i$ -th type to be a piecewise function of $\delta_i$. In particular, $TA_i = -\alpha\delta_i^2$ if $\delta_i < 0$ and $TA_i = \beta\sqrt{\delta_i}$ if $\delta_i \geq 0$.
> Here, $\alpha>0$ and $\beta>0$ would be parameters to control the desired tradeoff between weaknesses and resistances (by default, we could set something like $\alpha = \beta = 1$). Since $\delta_i$ is squared for negative values, it follows that large negative values of $\delta_i$ would be more heavily penalized than small negative values. On the flip side, since we take the square root of $\delta_i$ for non-negative values, it follows that large positive values of $\delta_i$ would not be rewarded much more than small positive values. 
> Finally, I propose that we define the `balance` metric of a team as follows: $balance = \sum_iTA_i$. Positive values of `balance` would indicate a well-balanced team, and negative values would indicate a team that could use improvement. 

Now the goal of the `recommend` function would be: `"given an input list of up 5 pokemon, determine which pokemon should be added to the team to maximize its 'balance' metric"`. This could be accomplished via a simple brute-force search since the total number of pokemon is not very large.

**Comment by j99thoms** [comment]
Please let me know your thoughts on the above suggestions @AguilarRaul  @ritisha2000  @snesunil.

**Comment by j99thoms** [comment]
> **1. Rename `add_team_members` to `get_types`**

See https://github.com/UBC-MDS/pokehelpyer/commit/d73b8ba9899a55cbb3860556cff7b568afbea7c0 for a mockup of these suggestions.

**Comment by j99thoms** [comment]
> **2. Consider the existence of dual-type pokémon** 
> 
>  **3. Consider the existence of type immunities**

See https://github.com/UBC-MDS/pokehelpyer/commit/18db0ecf6029cda332644e32dac5272e7e4d6e67 and https://github.com/UBC-MDS/pokehelpyer/commit/a20cacb24a3e744cc30784c84081e91649676ef7 for a mockup of these suggestions.

**Comment by j99thoms** [comment]
> **4. Clarify the specifications of `recommend`**

See https://github.com/UBC-MDS/pokehelpyer/commit/275abd38f76e50cbd6016985fdd2c4321a97f8c3 and https://github.com/UBC-MDS/pokehelpyer/commit/ed82989cf7dce820107f082db52892d43581b1fc for a mockup of these suggestions.

**Comment by j99thoms** [comment]
By the way, I should probably mention that I'd be fine with taking on the development of both `recommend` as well as the new function `calc_balance`.

**Comment by j99thoms** [comment]
Closed with https://github.com/UBC-MDS/pokehelpyer/pull/23.

**Comment by AguilarRaul** [comment]
I missed 2.2 implementation, for now, the code is adding 1 any type regardless of whether this type is also a weakness for the same Pokemon. I will fix it later today. All other specifications were implemented.
