### ISSUE TITLE
Broken link in README.

### ISSUE THREAD

**Issue by j99thoms** [UBC-MDS/pokehelpyer#22]
The link to the code of conduct in the README is broken. Currently, it is [https://github.com/UBC-MDS/pokehelpyer/blob/**contributing**/CONDUCT.md](https://github.com/UBC-MDS/pokehelpyer/blob/contributing/CONDUCT.md), but it should be replaced with [https://github.com/UBC-MDS/pokehelpyer/blob/**main**/CONDUCT.md](https://github.com/UBC-MDS/pokehelpyer/blob/main/CONDUCT.md).

We need to be careful to only use links to content in the main branch. Other branches may be deleted after merging with main, which results in these dead links. 

Edit: Looks like their are actually two broken links. The link to the second dataset, `chart.csv`, should be updated to https://github.com/zonination/pokemon-chart/blob/master/chart.csv (the current link is https://github.com/zonination/pokémon-chart/blob/master/chart.csv with an `é` instead of an `e`, which breaks it).

**Comment by ritisha2000** [comment]
Thanks for pointing it out. I'll correct it.

**Comment by j99thoms** [comment]
Closed with https://github.com/UBC-MDS/pokehelpyer/pull/24.
