### ISSUE TITLE
Create project structure

### ISSUE THREAD

**Issue by ritisha2000** [UBC-MDS/pokehelpyer#3]
"Create [project structure for the python package](https://py-pkgs.org/03-how-to-package-a-python) and push it as a public repository in the [UBC-MDS organization](https://github.com/UBC-MDS/) on Github.com.

The name of the repository should be relevant to the package/project topics."

**Comment by j99thoms** [comment]
Completed with https://github.com/UBC-MDS/pokehelpyer/pull/1.
