### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/pokehelpyer#46]
**Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

## 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}
Good Job!

#### 1. Create project structure for the R project
rubric={mechanics:20}

- [x] There isn't a recognizable project structure for the R package (no `man`, `R`, `docs` folders present) - **mechanics -2**.   
**Comment:** Missing man or docs directory 

## 4. R package function specifications
rubric={quality:10}
Good Job!

## 5. Specific expectations for this milestone are:
rubric={mechanics:10}
Good Job!

## 6. Submission instructions
rubric={mechanics:10}
Good Job!

**Comment by AguilarRaul** [comment]
Closed with https://github.com/UBC-MDS/pokehelperr/commit/ef8a88a94dbfa442b6f351d50de224b22ffc9cfb in R repo
