### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ritisha2000** [UBC-MDS/pokehelpyer#9]
"Agree upon a collaboration strategy that describes how you will work together on this project and edit CONTRIBUTING.md to reflect your strategy. Again, there will be a default version of this file. You can use it as is or adapt it with appropriate attribution."

**Comment by j99thoms** [comment]
Completed with https://github.com/UBC-MDS/pokehelpyer/pull/8 and https://github.com/UBC-MDS/pokehelpyer/pull/18.
